import bcrypt from 'bcrypt';
import User from '../models/User.js';
import Vendor from '../models/Vendor.js';
import HoneymoonDestination from '../models/HoneymoonDestination.js';
import Horoscope from '../models/Horoscope.js';
import logger from '../utils/logger.js';

const CITY_COORDS = {
  Colombo: { latitude: 6.9271, longitude: 79.8612 },
  Kandy: { latitude: 7.2906, longitude: 80.6337 },
  Galle: { latitude: 6.0535, longitude: 80.221 },
  Jaffna: { latitude: 9.6615, longitude: 80.0255 },
  Negombo: { latitude: 7.2084, longitude: 79.8358 },
  Kurunegala: { latitude: 7.4863, longitude: 80.3647 },
  Gampaha: { latitude: 7.0907, longitude: 79.9997 },
  Matara: { latitude: 5.9549, longitude: 80.5550 },
};

function horoscope(city, dateOfBirth, timeOfBirth, overrides = {}) {
  const coords = CITY_COORDS[city] || CITY_COORDS.Colombo;
  return {
    dateOfBirth,
    timeOfBirth,
    placeOfBirth: {
      ...coords,
      timezone: 'Asia/Colombo',
      city,
      country: 'Sri Lanka',
    },
    ...overrides,
  };
}

function mapHoroscopeFields(horoscopeValue) {
  if (!horoscopeValue) {
    return {};
  }

  return {
    birthData: {
      dateOfBirth: horoscopeValue.dateOfBirth,
      timeOfBirth: horoscopeValue.timeOfBirth,
      placeOfBirth: horoscopeValue.placeOfBirth,
      knownBirthTime: true,
    },
    horoscopeData: {
      zodiacSign: horoscopeValue.moonSign || horoscopeValue.rashi || 'Unknown',
      moonSign: horoscopeValue.moonSign,
      rashi: horoscopeValue.rashi,
      nakshatra: horoscopeValue.nakshatra,
    },
  };
}

const baseUsers = [
  {
    email: 'admin@raashilink.ai',
    password: 'password123',
    role: 'admin',
    personalInfo: {
      firstName: 'Admin',
      lastName: 'User',
      phone: '+94770000001',
      bio: 'Platform administrator for RaashiLink.AI.',
      location: 'Sri Lanka',
    },
  },
  {
    email: 'shanuka@gmail.com',
    password: '11111111',
    forcePasswordSync: true,
    role: 'user',
    personalInfo: {
      firstName: 'Shanuka',
      lastName: 'Jayasinghe',
      phone: '+94770000003',
      age: 28,
      location: 'Colombo',
      gender: 'male',
      tagline: 'Grounded values, modern mindset.',
      bio: 'Product engineer looking for a serious relationship leading to marriage.',
      ethnicity: 'Sinhalese',
      height: "5'10\"",
      photos: [],
    },
    horoscope: horoscope('Colombo', new Date('1997-11-15'), '08:30', {
      nakshatra: 'Jyeshtha',
      rashi: 'Scorpio',
      moonSign: 'Scorpio',
    }),
    personality: {
      openness: 0.84,
      conscientiousness: 0.79,
      extraversion: 0.65,
      agreeableness: 0.8,
      neuroticism: 0.35,
    },
    lifestyle: {
      religion: 'Buddhist',
      diet: 'Non-veg',
      smoking: 'Never',
      drinking: 'Never',
      preferredLocation: 'Colombo',
      familyValues: 0.9,
      educationLevel: 'BSc Computer Science',
      professionType: 'Product Engineering',
      familyPlans: 'Looking to settle down in the next 2-3 years',
      hobbies: ['Reading', 'Badminton', 'Travel'],
      languages: ['Sinhala', 'English'],
    },
  },
];

const demoVendorAccounts = [
  {
    email: 'vendor.goldenlotus@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Nuwan',
      lastName: 'Perera',
      phone: '+94770000012',
      location: 'Colombo 07',
      bio: 'Lead photographer specialising in luxury wedding storytelling and cinematic coverage.',
    },
    vendorProfile: {
      businessName: 'Golden Lotus Events',
      businessCategory: 'Photography',
      portfolioUrl: 'https://goldenlotusevents.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Full-day wedding coverage', 'Pre-shoot package', 'Same-day highlight reel'],
    },
  },
  {
    email: 'vendor.spicegarden@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Harshi',
      lastName: 'Fernando',
      phone: '+94770000013',
      location: 'Negombo',
      bio: 'Wedding caterer delivering curated Sri Lankan and international menus for large celebrations.',
    },
    vendorProfile: {
      businessName: 'Spice Garden Catering',
      businessCategory: 'Catering',
      portfolioUrl: 'https://spicegardencatering.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Buffet menus', 'Live food stations', 'Dessert bars'],
    },
  },
  {
    email: 'vendor.pearlgrand@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Malith',
      lastName: 'Senanayake',
      phone: '+94770000014',
      location: 'Colombo 03',
      bio: 'Venue manager for luxury ballroom and garden weddings in Colombo.',
    },
    vendorProfile: {
      businessName: 'Pearl Grand Venue',
      businessCategory: 'Venue',
      portfolioUrl: 'https://pearlgrandvenue.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Grand ballroom', 'Garden ceremony setup', 'Bridal suite access'],
    },
  },
  {
    email: 'vendor.blossomdecor@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Sachini',
      lastName: 'Rathnayake',
      phone: '+94770000015',
      location: 'Kandy',
      bio: 'Floral designer focused on elegant poruwa, stage, and reception styling.',
    },
    vendorProfile: {
      businessName: 'Blossom Floral Decor',
      businessCategory: 'Decor',
      portfolioUrl: 'https://blossomdecor.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Poruwa florals', 'Reception styling', 'Fresh flower installations'],
    },
  },
  {
    email: 'vendor.signaturebridal@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Dineli',
      lastName: 'Silva',
      phone: '+94770000016',
      location: 'Colombo 05',
      bio: 'Designer of bespoke bridal sarees, lehengas, and reception gowns.',
    },
    vendorProfile: {
      businessName: 'Signature Bridal Couture',
      businessCategory: 'Attire',
      portfolioUrl: 'https://signaturebridal.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Custom bridal wear', 'Bridesmaid styling', 'Alteration support'],
    },
  },
  {
    email: 'vendor.rhythmbeats@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Ravindu',
      lastName: 'Jayasuriya',
      phone: '+94770000017',
      location: 'Colombo',
      bio: 'Live entertainment provider for wedding receptions, homecomings, and afterparties.',
    },
    vendorProfile: {
      businessName: 'Rhythm & Beats',
      businessCategory: 'Music',
      portfolioUrl: 'https://rhythmbeats.example.com',
      verificationStatus: 'verified',
      packageSummary: ['DJ sets', 'Live band', 'Traditional entrance drummers'],
    },
  },
  {
    email: 'vendor.eternalmoments@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Iresha',
      lastName: 'Goonetilleke',
      phone: '+94770000018',
      location: 'Colombo 04',
      bio: 'Planner coordinating timelines, vendors, guest logistics, and event-day execution.',
    },
    vendorProfile: {
      businessName: 'Eternal Moments Planning',
      businessCategory: 'Planner',
      portfolioUrl: 'https://eternalmoments.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Full planning', 'Month-of coordination', 'Destination wedding support'],
    },
  },
  {
    email: 'vendor.islandhorizons@raashilink.ai',
    password: 'password123',
    role: 'vendor',
    personalInfo: {
      firstName: 'Dulani',
      lastName: 'Wijeratne',
      phone: '+94770000019',
      location: 'Mirissa',
      bio: 'Travel specialist handling honeymoons, guest transport, and destination wedding logistics.',
    },
    vendorProfile: {
      businessName: 'Island Horizons Travel',
      businessCategory: 'Travel',
      portfolioUrl: 'https://islandhorizons.example.com',
      verificationStatus: 'verified',
      packageSummary: ['Honeymoon itineraries', 'Airport transfers', 'Guest accommodation coordination'],
    },
  },
];

const extraVendorAccounts = [
  ['vendor.lakeview@raashilink.ai', 'Ayesha', 'Fernando', '+94770000020', 'Kandy', 'Lake View Grand', 'Venue'],
  ['vendor.coastalpavilion@raashilink.ai', 'Roshan', 'De Mel', '+94770000021', 'Galle', 'Coastal Pavilion', 'Venue'],
  ['vendor.silverframe@raashilink.ai', 'Pasindu', 'Dias', '+94770000022', 'Kandy', 'Silver Frame Studios', 'Photography'],
  ['vendor.aislememory@raashilink.ai', 'Madhavi', 'Peris', '+94770000023', 'Galle', 'Aisle Memory Films', 'Photography'],
  ['vendor.royalfeast@raashilink.ai', 'Thilini', 'Karunaratne', '+94770000024', 'Colombo', 'Royal Feast Caterers', 'Catering'],
  ['vendor.saffronbanquet@raashilink.ai', 'Imran', 'Fazil', '+94770000025', 'Kandy', 'Saffron Banquet', 'Catering'],
  ['vendor.petalatelier@raashilink.ai', 'Nimesha', 'Madushani', '+94770000026', 'Colombo', 'Petal Atelier', 'Decor'],
  ['vendor.ivyleaf@raashilink.ai', 'Gayan', 'Hettiarachchi', '+94770000027', 'Galle', 'Ivy Leaf Weddings', 'Decor'],
  ['vendor.silkandstone@raashilink.ai', 'Vihangi', 'Senaratne', '+94770000028', 'Kandy', 'Silk & Stone Bridal', 'Attire'],
  ['vendor.celestialcouture@raashilink.ai', 'Shenali', 'Abeywickrama', '+94770000029', 'Colombo', 'Celestial Couture', 'Attire'],
  ['vendor.velvetvoice@raashilink.ai', 'Kushan', 'Fernando', '+94770000030', 'Negombo', 'Velvet Voice Collective', 'Music'],
  ['vendor.sunsetgroove@raashilink.ai', 'Anuki', 'Mendis', '+94770000031', 'Matara', 'Sunset Groove', 'Music'],
  ['vendor.blushandbloom@raashilink.ai', 'Piumi', 'Perera', '+94770000032', 'Colombo', 'Blush & Bloom Beauty', 'Makeup'],
  ['vendor.radiantbridal@raashilink.ai', 'Hashini', 'Ranatunga', '+94770000033', 'Kandy', 'Radiant Bridal Studio', 'Makeup'],
  ['vendor.lotusglam@raashilink.ai', 'Fathima', 'Rizna', '+94770000034', 'Negombo', 'Lotus Glam Lounge', 'Makeup'],
].map(([email, firstName, lastName, phone, location, businessName, businessCategory]) => ({
  email,
  password: 'password123',
  role: 'vendor',
  personalInfo: {
    firstName,
    lastName,
    phone,
    location,
    bio: `${businessName} is a verified ${businessCategory.toLowerCase()} business serving weddings across Sri Lanka.`,
  },
  vendorProfile: {
    businessName,
    businessCategory,
    portfolioUrl: `https://${String(businessName).toLowerCase().replace(/[^a-z0-9]+/g, '')}.example.com`,
    verificationStatus: 'verified',
    packageSummary: ['Standard package', 'Premium package', 'Custom package'],
  },
}));

function buildCandidateUsers() {
  const profiles = [
    {
      firstName: 'Nadeesha',
      lastName: 'Perera',
      email: 'nadeesha.perera@raashilink.ai',
      phone: '+94770001001',
      age: 26,
      location: 'Colombo',
      religion: 'Buddhist',
      professionType: 'Software Engineering',
      educationLevel: 'BSc Information Technology',
      familyValues: 0.91,
      openness: 0.82,
      conscientiousness: 0.81,
      extraversion: 0.63,
      agreeableness: 0.86,
      neuroticism: 0.24,
      city: 'Colombo',
      dob: '1999-06-03',
      tob: '07:10',
      nakshatra: 'Pushya',
      rashi: 'Cancer',
      moonSign: 'Cancer',
      bio: 'Engineer with strong family values and a calm, optimistic outlook.',
    },
    {
      firstName: 'Ishari',
      lastName: 'Ranasinghe',
      email: 'ishari.ranasinghe@raashilink.ai',
      phone: '+94770001002',
      age: 27,
      location: 'Kandy',
      religion: 'Buddhist',
      professionType: 'Medical Officer',
      educationLevel: 'MBBS',
      familyValues: 0.94,
      openness: 0.75,
      conscientiousness: 0.87,
      extraversion: 0.57,
      agreeableness: 0.9,
      neuroticism: 0.25,
      city: 'Kandy',
      dob: '1998-11-09',
      tob: '05:50',
      nakshatra: 'Rohini',
      rashi: 'Taurus',
      moonSign: 'Taurus',
      bio: 'Doctor who values trust, stability, and shared long-term goals.',
    },
    {
      firstName: 'Chathuri',
      lastName: 'Fernando',
      email: 'chathuri.fernando@raashilink.ai',
      phone: '+94770001003',
      age: 25,
      location: 'Gampaha',
      religion: 'Catholic',
      professionType: 'UX Designer',
      educationLevel: 'BDes',
      familyValues: 0.84,
      openness: 0.9,
      conscientiousness: 0.69,
      extraversion: 0.71,
      agreeableness: 0.8,
      neuroticism: 0.3,
      city: 'Negombo',
      dob: '2000-03-20',
      tob: '13:15',
      nakshatra: 'Swati',
      rashi: 'Libra',
      moonSign: 'Libra',
      bio: 'Creative and warm-hearted, hoping to build a grounded partnership.',
    },
    {
      firstName: 'Umasha',
      lastName: 'Jayawardena',
      email: 'umasha.jayawardena@raashilink.ai',
      phone: '+94770001004',
      age: 29,
      location: 'Matara',
      religion: 'Buddhist',
      professionType: 'Chartered Accountant',
      educationLevel: 'CIMA',
      familyValues: 0.88,
      openness: 0.72,
      conscientiousness: 0.9,
      extraversion: 0.52,
      agreeableness: 0.79,
      neuroticism: 0.28,
      city: 'Galle',
      dob: '1997-02-12',
      tob: '09:40',
      nakshatra: 'Anuradha',
      rashi: 'Scorpio',
      moonSign: 'Scorpio',
      bio: 'Finance professional with a practical mindset and deep commitment to family.',
    },
    {
      firstName: 'Kavini',
      lastName: 'Bandara',
      email: 'kavini.bandara@raashilink.ai',
      phone: '+94770001005',
      age: 24,
      location: 'Kurunegala',
      religion: 'Buddhist',
      professionType: 'Teacher',
      educationLevel: 'BA Education',
      familyValues: 0.92,
      openness: 0.7,
      conscientiousness: 0.82,
      extraversion: 0.6,
      agreeableness: 0.88,
      neuroticism: 0.22,
      city: 'Kurunegala',
      dob: '2001-08-01',
      tob: '11:05',
      nakshatra: 'Hasta',
      rashi: 'Virgo',
      moonSign: 'Virgo',
      bio: 'Teacher who values patience, kindness, and a peaceful home life.',
    },
    {
      firstName: 'Tharushi',
      lastName: 'Gunawardena',
      email: 'tharushi.gunawardena@raashilink.ai',
      phone: '+94770001006',
      age: 28,
      location: 'Colombo',
      religion: 'Buddhist',
      professionType: 'Data Analyst',
      educationLevel: 'BSc Statistics',
      familyValues: 0.86,
      openness: 0.81,
      conscientiousness: 0.84,
      extraversion: 0.55,
      agreeableness: 0.83,
      neuroticism: 0.27,
      city: 'Colombo',
      dob: '1998-05-17',
      tob: '10:20',
      nakshatra: 'Revati',
      rashi: 'Pisces',
      moonSign: 'Pisces',
      bio: 'Analytical and empathetic, looking for a mature and respectful partner.',
    },
    // ── New male profiles ────────────────────────────────────────────
    {
      firstName: 'Dinesh',
      lastName: 'Wijesinghe',
      email: 'dinesh.wijesinghe@raashilink.ai',
      phone: '+94770002001',
      age: 31,
      gender: 'male',
      location: 'Kandy',
      religion: 'Buddhist',
      professionType: 'Civil Engineer',
      educationLevel: 'BEng Civil Engineering',
      familyValues: 0.88,
      openness: 0.73,
      conscientiousness: 0.85,
      extraversion: 0.6,
      agreeableness: 0.82,
      neuroticism: 0.3,
      city: 'Kandy',
      dob: '1994-04-20',
      tob: '06:30',
      nakshatra: 'Bharani',
      rashi: 'Aries',
      moonSign: 'Aries',
      height: "5'11\"",
      ethnicity: 'Sinhalese',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Civil engineer who values discipline, family, and a peaceful life in the hills.',
    },
    {
      firstName: 'Ruwan',
      lastName: 'Pathirana',
      email: 'ruwan.pathirana@raashilink.ai',
      phone: '+94770002002',
      age: 34,
      gender: 'male',
      location: 'Colombo',
      religion: 'Buddhist',
      professionType: 'Lawyer',
      educationLevel: 'LLB',
      familyValues: 0.85,
      openness: 0.77,
      conscientiousness: 0.88,
      extraversion: 0.69,
      agreeableness: 0.79,
      neuroticism: 0.26,
      city: 'Colombo',
      dob: '1991-09-14',
      tob: '09:15',
      nakshatra: 'Hasta',
      rashi: 'Virgo',
      moonSign: 'Virgo',
      height: "6'0\"",
      ethnicity: 'Sinhalese',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Attorney with a sharp mind and a gentle heart, seeking a grounded life partner.',
    },
    {
      firstName: 'Kasun',
      lastName: 'Mendis',
      email: 'kasun.mendis@raashilink.ai',
      phone: '+94770002003',
      age: 27,
      gender: 'male',
      location: 'Gampaha',
      religion: 'Catholic',
      professionType: 'IT Consultant',
      educationLevel: 'BSc Computer Science',
      familyValues: 0.81,
      openness: 0.86,
      conscientiousness: 0.78,
      extraversion: 0.72,
      agreeableness: 0.84,
      neuroticism: 0.32,
      city: 'Gampaha',
      dob: '1998-06-05',
      tob: '14:45',
      nakshatra: 'Ardra',
      rashi: 'Gemini',
      moonSign: 'Gemini',
      height: "5'9\"",
      ethnicity: 'Sinhalese',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Tech consultant who loves deep conversations, travel, and building a meaningful future.',
    },
    {
      firstName: 'Tharaka',
      lastName: 'Silva',
      email: 'tharaka.silva@raashilink.ai',
      phone: '+94770002004',
      age: 38,
      gender: 'male',
      location: 'Galle',
      religion: 'Buddhist',
      professionType: 'Entrepreneur',
      educationLevel: 'MBA',
      familyValues: 0.9,
      openness: 0.8,
      conscientiousness: 0.82,
      extraversion: 0.75,
      agreeableness: 0.77,
      neuroticism: 0.24,
      city: 'Galle',
      dob: '1987-01-28',
      tob: '08:00',
      nakshatra: 'Shatabhisha',
      rashi: 'Aquarius',
      moonSign: 'Aquarius',
      height: "5'10\"",
      ethnicity: 'Sinhalese',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Business owner from Galle seeking a mature, caring partner to share life with.',
    },
    // ── New female profiles ──────────────────────────────────────────
    {
      firstName: 'Priya',
      lastName: 'Rajapaksha',
      email: 'priya.rajapaksha@raashilink.ai',
      phone: '+94770002005',
      age: 32,
      gender: 'female',
      location: 'Colombo',
      religion: 'Hindu',
      professionType: 'Marketing Manager',
      educationLevel: 'MBA Marketing',
      familyValues: 0.87,
      openness: 0.83,
      conscientiousness: 0.8,
      extraversion: 0.78,
      agreeableness: 0.85,
      neuroticism: 0.28,
      city: 'Colombo',
      dob: '1993-08-11',
      tob: '11:30',
      nakshatra: 'Purva Phalguni',
      rashi: 'Leo',
      moonSign: 'Leo',
      height: "5'5\"",
      ethnicity: 'Tamil',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Marketing professional who values ambition, warmth, and a strong family bond.',
    },
    {
      firstName: 'Ashni',
      lastName: 'Ratnayake',
      email: 'ashni.ratnayake@raashilink.ai',
      phone: '+94770002006',
      age: 35,
      gender: 'female',
      location: 'Jaffna',
      religion: 'Hindu',
      professionType: 'University Lecturer',
      educationLevel: 'PhD Literature',
      familyValues: 0.89,
      openness: 0.88,
      conscientiousness: 0.86,
      extraversion: 0.54,
      agreeableness: 0.91,
      neuroticism: 0.21,
      city: 'Jaffna',
      dob: '1990-11-03',
      tob: '07:45',
      nakshatra: 'Anuradha',
      rashi: 'Scorpio',
      moonSign: 'Scorpio',
      height: "5'4\"",
      ethnicity: 'Tamil',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Academic who finds joy in learning, literature, and quiet evenings with loved ones.',
    },
    {
      firstName: 'Nilufar',
      lastName: 'De Silva',
      email: 'nilufar.desilva@raashilink.ai',
      phone: '+94770002007',
      age: 30,
      gender: 'female',
      location: 'Colombo',
      religion: 'Catholic',
      professionType: 'Architect',
      educationLevel: 'BArch',
      familyValues: 0.83,
      openness: 0.91,
      conscientiousness: 0.76,
      extraversion: 0.68,
      agreeableness: 0.81,
      neuroticism: 0.33,
      city: 'Colombo',
      dob: '1995-03-22',
      tob: '10:50',
      nakshatra: 'Ashwini',
      rashi: 'Aries',
      moonSign: 'Aries',
      height: "5'6\"",
      ethnicity: 'Burgher',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Architect with a creative soul, looking for a partner who appreciates beauty and adventure.',
    },
    {
      firstName: 'Chamari',
      lastName: 'Wickramasinghe',
      email: 'chamari.wickramasinghe@raashilink.ai',
      phone: '+94770002008',
      age: 36,
      gender: 'female',
      location: 'Kurunegala',
      religion: 'Buddhist',
      professionType: 'Pharmacist',
      educationLevel: 'BPharm',
      familyValues: 0.93,
      openness: 0.69,
      conscientiousness: 0.89,
      extraversion: 0.56,
      agreeableness: 0.9,
      neuroticism: 0.2,
      city: 'Kurunegala',
      dob: '1989-07-17',
      tob: '16:20',
      nakshatra: 'Pushya',
      rashi: 'Cancer',
      moonSign: 'Cancer',
      height: "5'3\"",
      ethnicity: 'Sinhalese',
      password: '11111111',
      forcePasswordSync: true,
      bio: 'Pharmacist who believes in quiet strength, loyalty, and building a nurturing home.',
    },
  ];

  return profiles.map((profile, index) => ({
    email: profile.email,
    password: profile.password || 'password123',
    forcePasswordSync: profile.forcePasswordSync || false,
    role: 'user',
    personalInfo: {
      firstName: profile.firstName,
      lastName: profile.lastName,
      phone: profile.phone,
      age: profile.age,
      location: profile.location,
      gender: profile.gender || 'female',
      bio: profile.bio,
      ethnicity: profile.ethnicity || 'Sinhalese',
      height: profile.height || `${5 + ((index + 2) % 2)}'${3 + (index % 5)}"`,
      photos: [],
    },
    horoscope: horoscope(profile.city, new Date(profile.dob), profile.tob, {
      nakshatra: profile.nakshatra,
      rashi: profile.rashi,
      moonSign: profile.moonSign,
    }),
    personality: {
      openness: profile.openness,
      conscientiousness: profile.conscientiousness,
      extraversion: profile.extraversion,
      agreeableness: profile.agreeableness,
      neuroticism: profile.neuroticism,
    },
    lifestyle: {
      religion: profile.religion,
      diet: 'Non-veg',
      smoking: 'Never',
      drinking: 'Never',
      preferredLocation: 'Colombo',
      familyValues: profile.familyValues,
      educationLevel: profile.educationLevel,
      professionType: profile.professionType,
      familyPlans: 'Looking for a stable relationship with long-term commitment.',
      hobbies: ['Reading', 'Travel', 'Music'],
      languages: ['Sinhala', 'English'],
    },
  }));
}

const demoUsers = [...baseUsers, ...demoVendorAccounts, ...extraVendorAccounts, ...buildCandidateUsers()];
const LEGACY_DEMO_EMAILS = [
  'user@raashilink.ai',
  'anjali@raashilink.ai',
  'dilshan@raashilink.ai',
  'kavindi@raashilink.ai',
];

export const DEMO_USER_EMAILS = demoUsers.map((entry) => entry.email);

const passwordHashCache = new Map();

async function getSeedPasswordHash(password = 'password123') {
  if (!passwordHashCache.has(password)) {
    passwordHashCache.set(password, bcrypt.hash(password, 10));
  }

  return passwordHashCache.get(password);
}

export async function seedDemoUsers() {
  const verification = {
    emailVerified: true,
    phoneVerified: true,
    emailVerifiedAt: new Date(),
    phoneVerifiedAt: new Date(),
  };

  await Promise.all(
    demoUsers.map(async (entry) => {
      const passwordHash = await getSeedPasswordHash(entry.password);
      const existingUser = await User.findOne({ email: entry.email }).select('_id').lean();

      await User.updateOne(
        { email: entry.email },
        {
          $setOnInsert: {
            ...entry,
            ...mapHoroscopeFields(entry.horoscope),
            passwordHash,
            verification,
          },
        },
        { upsert: true }
      );

      const updates = {
        // Only set verification for NEW users ($setOnInsert handles it above).
        // Existing users keep their real verification state so resets are not overwritten on restart.
        ...(!existingUser ? { verification } : {}),
        // Always sync gender so DB stays consistent with seed data.
        ...(entry.personalInfo?.gender ? { 'personalInfo.gender': entry.personalInfo.gender } : {}),
        // Preserve real user edits on restart. Seed horoscope/birth only for first-time inserts.
        ...(!existingUser && entry.horoscope ? mapHoroscopeFields(entry.horoscope) : {}),
      };

      await User.updateOne(
        { email: entry.email },
        {
          $set: updates,
        }
      );

      if (entry.forcePasswordSync) {
        await User.updateOne(
          { email: entry.email },
          {
            $set: { passwordHash },
          }
        );
      }
    })
  );

  await User.deleteMany({ email: { $in: LEGACY_DEMO_EMAILS } });

  const DEMO_VENDORS = [
    {
      ownerEmail: 'vendor.goldenlotus@raashilink.ai',
      businessName: 'Golden Lotus Events',
      category: 'Photography',
      description: 'Award-winning wedding photography and cinematic videography for Kandyan, Christian, Hindu, and beachfront weddings across Sri Lanka.',
      city: 'Colombo',
      address: '14 Alfred House Gardens, Colombo 03',
      contactPhone: '+94 77 345 1200',
      contactEmail: 'hello@goldenlotusevents.example.com',
      website: 'https://goldenlotusevents.example.com',
      serviceArea: ['Colombo', 'Kandy', 'Galle', 'Bentota'],
      pricingRange: { min: 150000, max: 450000, currency: 'LKR' },
      featuredServices: ['Full-day wedding coverage', 'Engagement shoots', 'Cinematic highlight film'],
      packageSummary: ['10-hour coverage', 'Two photographers', 'Drone add-on available'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 30,
      capacity: { minGuests: 50, maxGuests: 800 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&q=75',
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=75',
      ],
      ratings: { average: 4.8, count: 24 },
    },
    {
      ownerEmail: 'vendor.spicegarden@raashilink.ai',
      businessName: 'Spice Garden Catering',
      category: 'Catering',
      description: 'Premium Sri Lankan, fusion, and international buffet catering with halal-friendly and vegetarian menu planning for large weddings.',
      city: 'Negombo',
      address: '82 Lewis Place, Negombo',
      contactPhone: '+94 77 412 8899',
      contactEmail: 'bookings@spicegardencatering.example.com',
      website: 'https://spicegardencatering.example.com',
      serviceArea: ['Colombo', 'Negombo', 'Gampaha', 'Kalutara'],
      pricingRange: { min: 200000, max: 1200000, currency: 'LKR' },
      featuredServices: ['Buffet catering', 'Live hoppers station', 'Dessert room styling'],
      packageSummary: ['Silver buffet', 'Gold buffet', 'Custom premium menu'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 21,
      capacity: { minGuests: 100, maxGuests: 1500 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=75',
        'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=75',
      ],
      ratings: { average: 4.6, count: 38 },
    },
    {
      ownerEmail: 'vendor.pearlgrand@raashilink.ai',
      businessName: 'Pearl Grand Venue',
      category: 'Venue',
      description: 'Luxury ballroom and outdoor garden venue in central Colombo with bridal suite, valet parking, and in-house coordination support.',
      city: 'Colombo',
      address: '220 Galle Road, Colombo 03',
      contactPhone: '+94 11 244 8800',
      contactEmail: 'events@pearlgrandvenue.example.com',
      website: 'https://pearlgrandvenue.example.com',
      serviceArea: ['Colombo'],
      pricingRange: { min: 500000, max: 3000000, currency: 'LKR' },
      featuredServices: ['Ballroom reception', 'Garden ceremony', 'Bridal suite'],
      packageSummary: ['Emerald package', 'Pearl package', 'Signature buyout'],
      responseTime: 'Usually responds within 1 hour',
      leadTimeDays: 45,
      capacity: { minGuests: 120, maxGuests: 650 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=75',
        'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=75',
      ],
      ratings: { average: 4.9, count: 52 },
    },
    {
      ownerEmail: 'vendor.blossomdecor@raashilink.ai',
      businessName: 'Blossom Floral Decor',
      category: 'Decor',
      description: 'Elegant floral arrangements, poruwa decor, stage styling, and aisle installations tailored to luxury and traditional wedding themes.',
      city: 'Kandy',
      address: '31 Peradeniya Road, Kandy',
      contactPhone: '+94 81 221 7788',
      contactEmail: 'studio@blossomdecor.example.com',
      website: 'https://blossomdecor.example.com',
      serviceArea: ['Colombo', 'Kandy', 'Kurunegala', 'Nuwara Eliya'],
      pricingRange: { min: 80000, max: 600000, currency: 'LKR' },
      featuredServices: ['Poruwa florals', 'Reception stage styling', 'Table centerpieces'],
      packageSummary: ['Fresh florals package', 'Luxury stage package', 'Full decor concept'],
      responseTime: 'Usually responds within 3 hours',
      leadTimeDays: 14,
      capacity: { minGuests: 50, maxGuests: 1000 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=75',
        'https://images.unsplash.com/photo-1487530811015-780c2fde6bef?w=800&q=75',
      ],
      ratings: { average: 4.7, count: 19 },
    },
    {
      ownerEmail: 'vendor.signaturebridal@raashilink.ai',
      businessName: 'Signature Bridal Couture',
      category: 'Attire',
      description: 'Custom bridal lehengas, sarees, osari draping support, and western gowns with fittings and alteration services.',
      city: 'Colombo',
      address: '112 Havelock Road, Colombo 05',
      contactPhone: '+94 77 998 2200',
      contactEmail: 'couture@signaturebridal.example.com',
      website: 'https://signaturebridal.example.com',
      serviceArea: ['Colombo', 'Galle', 'Matara'],
      pricingRange: { min: 120000, max: 800000, currency: 'LKR' },
      featuredServices: ['Bridal sarees', 'Reception gowns', 'Bridesmaid coordination'],
      packageSummary: ['Made-to-measure bridal wear', 'Premium fitting package', 'Homecoming look'],
      responseTime: 'Usually responds within 6 hours',
      leadTimeDays: 30,
      capacity: { minGuests: 1, maxGuests: 20 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1594552072238-b8a33785b6cd?w=800&q=75',
        'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&q=75',
      ],
      ratings: { average: 4.5, count: 31 },
    },
    {
      ownerEmail: 'vendor.rhythmbeats@raashilink.ai',
      businessName: 'Rhythm & Beats',
      category: 'Music',
      description: 'Live bands, DJs, saxophone sets, and traditional Baila orchestras for receptions, entrance moments, and afterparties.',
      city: 'Colombo',
      address: '55 Park Street, Colombo 02',
      contactPhone: '+94 77 661 4400',
      contactEmail: 'hello@rhythmbeats.example.com',
      website: 'https://rhythmbeats.example.com',
      serviceArea: ['Colombo', 'Kandy', 'Negombo', 'Galle'],
      pricingRange: { min: 60000, max: 350000, currency: 'LKR' },
      featuredServices: ['DJ performance', 'Live wedding band', 'Traditional drummers'],
      packageSummary: ['Reception DJ set', 'Live band premium', 'Custom entertainment lineup'],
      responseTime: 'Usually responds within 5 hours',
      leadTimeDays: 10,
      capacity: { minGuests: 50, maxGuests: 2000 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=75',
      ],
      ratings: { average: 4.4, count: 45 },
    },
    {
      ownerEmail: 'vendor.eternalmoments@raashilink.ai',
      businessName: 'Eternal Moments Planning',
      category: 'Planner',
      description: 'Full-service wedding planning and event management from engagement to honeymoon, with timeline, logistics, and vendor coordination.',
      city: 'Colombo',
      address: '8 Marine Drive, Colombo 04',
      contactPhone: '+94 77 300 2211',
      contactEmail: 'team@eternalmoments.example.com',
      website: 'https://eternalmoments.example.com',
      serviceArea: ['Colombo', 'Kandy', 'Galle', 'Kurunegala', 'Nuwara Eliya'],
      pricingRange: { min: 250000, max: 1000000, currency: 'LKR' },
      featuredServices: ['Full planning', 'On-the-day coordination', 'Vendor management'],
      packageSummary: ['Essentials planning', 'Full-service planning', 'Destination management'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 20,
      capacity: { minGuests: 80, maxGuests: 1200 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=75',
      ],
      ratings: { average: 4.9, count: 17 },
    },
    {
      ownerEmail: 'vendor.islandhorizons@raashilink.ai',
      businessName: 'Island Horizons Travel',
      category: 'Travel',
      description: 'Honeymoon packages, luxury transfers, guest transport coordination, and destination wedding logistics for island-wide celebrations.',
      city: 'Mirissa',
      address: '17 Beach Road, Mirissa',
      contactPhone: '+94 41 225 4433',
      contactEmail: 'travel@islandhorizons.example.com',
      website: 'https://islandhorizons.example.com',
      serviceArea: ['Colombo', 'Galle', 'Nuwara Eliya', 'Mirissa'],
      pricingRange: { min: 300000, max: 2000000, currency: 'LKR' },
      featuredServices: ['Honeymoon planning', 'Airport pickup', 'Destination logistics'],
      packageSummary: ['South coast honeymoon', 'Hill country honeymoon', 'Destination wedding logistics'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 18,
      capacity: { minGuests: 2, maxGuests: 500 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=75',
      ],
      ratings: { average: 4.6, count: 28 },
    },
    {
      ownerEmail: 'vendor.lakeview@raashilink.ai',
      businessName: 'Lake View Grand',
      category: 'Venue',
      description: 'Hill-country ballroom venue with lake views, bridal suite access, and indoor-outdoor ceremony spaces.',
      city: 'Kandy',
      address: '44 Sangaraja Mawatha, Kandy',
      contactPhone: '+94 81 555 1200',
      contactEmail: 'events@lakeviewgrand.example.com',
      website: 'https://lakeviewgrand.example.com',
      serviceArea: ['Kandy', 'Peradeniya'],
      pricingRange: { min: 450000, max: 2200000, currency: 'LKR' },
      featuredServices: ['Ballroom receptions', 'Garden ceremonies', 'Bridal prep suite'],
      packageSummary: ['Classic ballroom', 'Lake garden package', 'Full property buyout'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 30,
      capacity: { minGuests: 100, maxGuests: 500 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=75',
        'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=75',
      ],
      ratings: { average: 4.7, count: 33 },
    },
    {
      ownerEmail: 'vendor.coastalpavilion@raashilink.ai',
      businessName: 'Coastal Pavilion',
      category: 'Venue',
      description: 'Beachside wedding venue for sunset ceremonies, receptions, and homecoming celebrations in the south coast.',
      city: 'Galle',
      address: '9 Lighthouse Street, Galle Fort',
      contactPhone: '+94 91 778 3300',
      contactEmail: 'hello@coastalpavilion.example.com',
      website: 'https://coastalpavilion.example.com',
      serviceArea: ['Galle', 'Unawatuna', 'Bentota'],
      pricingRange: { min: 400000, max: 2500000, currency: 'LKR' },
      featuredServices: ['Beach ceremonies', 'Reception pavilion', 'Guest room blocks'],
      packageSummary: ['Sunset ceremony', 'South coast reception', 'Destination wedding package'],
      responseTime: 'Usually responds within 3 hours',
      leadTimeDays: 35,
      capacity: { minGuests: 80, maxGuests: 420 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1510076857177-7470076d4098?w=800&q=75',
        'https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=800&q=75',
      ],
      ratings: { average: 4.8, count: 29 },
    },
    {
      ownerEmail: 'vendor.silverframe@raashilink.ai',
      businessName: 'Silver Frame Studios',
      category: 'Photography',
      description: 'Documentary-style wedding photography with candid coverage and intimate portrait sessions.',
      city: 'Kandy',
      address: '16 Temple Street, Kandy',
      contactPhone: '+94 77 882 4100',
      contactEmail: 'book@silverframestudios.example.com',
      website: 'https://silverframestudios.example.com',
      serviceArea: ['Kandy', 'Nuwara Eliya', 'Kurunegala'],
      pricingRange: { min: 130000, max: 380000, currency: 'LKR' },
      featuredServices: ['Candid photography', 'Album design', 'Engagement shoots'],
      packageSummary: ['Story package', 'Album package', 'Cinematic photo-video combo'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 18,
      capacity: { minGuests: 50, maxGuests: 700 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=75',
        'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=75',
      ],
      ratings: { average: 4.6, count: 27 },
    },
    {
      ownerEmail: 'vendor.aislememory@raashilink.ai',
      businessName: 'Aisle Memory Films',
      category: 'Photography',
      description: 'Wedding photo and film studio specialising in cinematic storytelling and drone coverage.',
      city: 'Galle',
      address: '28 Colombo Road, Galle',
      contactPhone: '+94 77 445 7800',
      contactEmail: 'team@aislememoryfilms.example.com',
      website: 'https://aislememoryfilms.example.com',
      serviceArea: ['Galle', 'Matara', 'Colombo'],
      pricingRange: { min: 160000, max: 500000, currency: 'LKR' },
      featuredServices: ['Cinematic film', 'Drone coverage', 'Same-day teaser'],
      packageSummary: ['Film essentials', 'Photo + film', 'Signature cinema edit'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 21,
      capacity: { minGuests: 60, maxGuests: 900 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1507504031003-b417219a0fde?w=800&q=75',
        'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&q=75',
      ],
      ratings: { average: 4.9, count: 35 },
    },
    {
      ownerEmail: 'vendor.royalfeast@raashilink.ai',
      businessName: 'Royal Feast Caterers',
      category: 'Catering',
      description: 'Large-scale wedding catering with plated service, buffet stations, and dessert styling.',
      city: 'Colombo',
      address: '61 Duplication Road, Colombo 04',
      contactPhone: '+94 77 223 9911',
      contactEmail: 'events@royalfeast.example.com',
      website: 'https://royalfeast.example.com',
      serviceArea: ['Colombo', 'Kalutara', 'Panadura'],
      pricingRange: { min: 250000, max: 1400000, currency: 'LKR' },
      featuredServices: ['Plated dinner', 'Buffet service', 'Dessert styling'],
      packageSummary: ['Classic buffet', 'Grand reception menu', 'Curated plated dinner'],
      responseTime: 'Usually responds within 3 hours',
      leadTimeDays: 14,
      capacity: { minGuests: 100, maxGuests: 1800 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1464306076886-da185f6a9d05?w=800&q=75',
        'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=75',
      ],
      ratings: { average: 4.7, count: 42 },
    },
    {
      ownerEmail: 'vendor.saffronbanquet@raashilink.ai',
      businessName: 'Saffron Banquet',
      category: 'Catering',
      description: 'Kandyan and multi-cultural wedding menus with chef-led live counters and premium service crews.',
      city: 'Kandy',
      address: '12 William Gopallawa Mawatha, Kandy',
      contactPhone: '+94 77 108 6622',
      contactEmail: 'hello@saffronbanquet.example.com',
      website: 'https://saffronbanquet.example.com',
      serviceArea: ['Kandy', 'Matale', 'Kurunegala'],
      pricingRange: { min: 180000, max: 950000, currency: 'LKR' },
      featuredServices: ['Traditional menus', 'Live action stations', 'Wedding cake coordination'],
      packageSummary: ['Kandyan feast', 'Fusion reception menu', 'Premium custom menu'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 12,
      capacity: { minGuests: 80, maxGuests: 1200 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=75',
        'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=75',
      ],
      ratings: { average: 4.5, count: 21 },
    },
    {
      ownerEmail: 'vendor.petalatelier@raashilink.ai',
      businessName: 'Petal Atelier',
      category: 'Decor',
      description: 'Luxury floral design studio creating modern aisle styling, poruwa concepts, and reception installations.',
      city: 'Colombo',
      address: '27 Flower Road, Colombo 07',
      contactPhone: '+94 77 761 5544',
      contactEmail: 'studio@petalatelier.example.com',
      website: 'https://petalatelier.example.com',
      serviceArea: ['Colombo', 'Negombo', 'Gampaha'],
      pricingRange: { min: 95000, max: 700000, currency: 'LKR' },
      featuredServices: ['Luxury florals', 'Aisle styling', 'Reception centerpieces'],
      packageSummary: ['Poruwa styling', 'Reception florals', 'Full venue transformation'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 10,
      capacity: { minGuests: 50, maxGuests: 1200 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=800&q=75',
        'https://images.unsplash.com/photo-1487530811015-780c2fde6bef?w=800&q=75',
      ],
      ratings: { average: 4.8, count: 24 },
    },
    {
      ownerEmail: 'vendor.ivyleaf@raashilink.ai',
      businessName: 'Ivy Leaf Weddings',
      category: 'Decor',
      description: 'South-coast wedding decor team handling tropical florals, table styling, and intimate garden receptions.',
      city: 'Galle',
      address: '77 Wakwella Road, Galle',
      contactPhone: '+94 77 903 5521',
      contactEmail: 'design@ivyleafweddings.example.com',
      website: 'https://ivyleafweddings.example.com',
      serviceArea: ['Galle', 'Matara', 'Bentota'],
      pricingRange: { min: 70000, max: 520000, currency: 'LKR' },
      featuredServices: ['Garden decor', 'Tropical florals', 'Table styling'],
      packageSummary: ['Garden ceremony decor', 'Reception styling', 'Coastal luxe package'],
      responseTime: 'Usually responds within 5 hours',
      leadTimeDays: 9,
      capacity: { minGuests: 40, maxGuests: 800 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=75',
        'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800&q=75',
      ],
      ratings: { average: 4.6, count: 18 },
    },
    {
      ownerEmail: 'vendor.silkandstone@raashilink.ai',
      businessName: 'Silk & Stone Bridal',
      category: 'Attire',
      description: 'Bridal saree and reception gown atelier known for handwork, fittings, and custom styling.',
      city: 'Kandy',
      address: '8 Colombo Street, Kandy',
      contactPhone: '+94 77 440 2288',
      contactEmail: 'hello@silkandstonebridal.example.com',
      website: 'https://silkandstonebridal.example.com',
      serviceArea: ['Kandy', 'Kurunegala', 'Colombo'],
      pricingRange: { min: 90000, max: 650000, currency: 'LKR' },
      featuredServices: ['Bridal sarees', 'Reception gowns', 'Accessory styling'],
      packageSummary: ['Bridal saree package', 'Reception gown package', 'Full bridal styling'],
      responseTime: 'Usually responds within 6 hours',
      leadTimeDays: 20,
      capacity: { minGuests: 1, maxGuests: 25 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1525258946800-98cfd641d0de?w=800&q=75',
        'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=75',
      ],
      ratings: { average: 4.7, count: 26 },
    },
    {
      ownerEmail: 'vendor.celestialcouture@raashilink.ai',
      businessName: 'Celestial Couture',
      category: 'Attire',
      description: 'Luxury bridal wear studio for reception gowns, bridesmaid looks, and custom wedding-day styling.',
      city: 'Colombo',
      address: '145 Bauddhaloka Mawatha, Colombo 04',
      contactPhone: '+94 77 335 1190',
      contactEmail: 'couture@celestialcouture.example.com',
      website: 'https://celestialcouture.example.com',
      serviceArea: ['Colombo', 'Gampaha', 'Negombo'],
      pricingRange: { min: 140000, max: 900000, currency: 'LKR' },
      featuredServices: ['Reception gowns', 'Bridesmaid styling', 'Luxury fittings'],
      packageSummary: ['Reception couture', 'Bridesmaid capsule', 'Signature bridal look'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 25,
      capacity: { minGuests: 1, maxGuests: 30 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=75',
        'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&q=75',
      ],
      ratings: { average: 4.8, count: 30 },
    },
    {
      ownerEmail: 'vendor.velvetvoice@raashilink.ai',
      businessName: 'Velvet Voice Collective',
      category: 'Music',
      description: 'Live acoustic ensemble and reception band for elegant ceremonies and cocktail-hour entertainment.',
      city: 'Negombo',
      address: '23 Beach Road, Negombo',
      contactPhone: '+94 77 228 4411',
      contactEmail: 'bookings@velvetvoice.example.com',
      website: 'https://velvetvoice.example.com',
      serviceArea: ['Negombo', 'Colombo', 'Chilaw'],
      pricingRange: { min: 85000, max: 280000, currency: 'LKR' },
      featuredServices: ['Acoustic duo', 'Reception band', 'Ceremony music'],
      packageSummary: ['Acoustic set', 'Band performance', 'Ceremony + reception combo'],
      responseTime: 'Usually responds within 3 hours',
      leadTimeDays: 7,
      capacity: { minGuests: 50, maxGuests: 1000 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&q=75',
        'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=75',
      ],
      ratings: { average: 4.6, count: 20 },
    },
    {
      ownerEmail: 'vendor.sunsetgroove@raashilink.ai',
      businessName: 'Sunset Groove',
      category: 'Music',
      description: 'DJ and live entertainment team for beach weddings, homecomings, and afterparties.',
      city: 'Matara',
      address: '66 Beach Road, Matara',
      contactPhone: '+94 77 915 4400',
      contactEmail: 'events@sunsetgroove.example.com',
      website: 'https://sunsetgroove.example.com',
      serviceArea: ['Matara', 'Mirissa', 'Galle'],
      pricingRange: { min: 70000, max: 260000, currency: 'LKR' },
      featuredServices: ['DJ sets', 'Live percussion', 'Afterparty lighting'],
      packageSummary: ['Beach wedding DJ', 'Reception set', 'Party production package'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 6,
      capacity: { minGuests: 60, maxGuests: 1500 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=75',
        'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=75',
      ],
      ratings: { average: 4.5, count: 19 },
    },
    {
      ownerEmail: 'vendor.blushandbloom@raashilink.ai',
      businessName: 'Blush & Bloom Beauty',
      category: 'Makeup',
      description: 'Bridal hair and makeup artists for traditional, natural glam, and reception looks.',
      city: 'Colombo',
      address: '38 Thimbirigasyaya Road, Colombo 05',
      contactPhone: '+94 77 642 3100',
      contactEmail: 'hello@blushandbloombeauty.example.com',
      website: 'https://blushandbloombeauty.example.com',
      serviceArea: ['Colombo', 'Gampaha', 'Kalutara'],
      pricingRange: { min: 45000, max: 220000, currency: 'LKR' },
      featuredServices: ['Bridal makeup', 'Hair styling', 'Dressing assistance'],
      packageSummary: ['Bride only', 'Bride + entourage', 'Luxury bridal glam'],
      responseTime: 'Usually responds within 2 hours',
      leadTimeDays: 8,
      capacity: { minGuests: 1, maxGuests: 15 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=75',
        'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=75',
      ],
      ratings: { average: 4.9, count: 41 },
    },
    {
      ownerEmail: 'vendor.radiantbridal@raashilink.ai',
      businessName: 'Radiant Bridal Studio',
      category: 'Makeup',
      description: 'Kandyan bridal makeup and hairstyling studio offering on-location wedding-day services.',
      city: 'Kandy',
      address: '55 Yatinuwara Street, Kandy',
      contactPhone: '+94 77 278 4200',
      contactEmail: 'studio@radiantbridal.example.com',
      website: 'https://radiantbridal.example.com',
      serviceArea: ['Kandy', 'Matale', 'Nuwara Eliya'],
      pricingRange: { min: 50000, max: 240000, currency: 'LKR' },
      featuredServices: ['Kandyan bridal glam', 'Hair styling', 'Touch-up support'],
      packageSummary: ['Bride signature glam', 'Bride + bridesmaids', 'All-day artist support'],
      responseTime: 'Usually responds within 3 hours',
      leadTimeDays: 10,
      capacity: { minGuests: 1, maxGuests: 12 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=75',
        'https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800&q=75',
      ],
      ratings: { average: 4.8, count: 25 },
    },
    {
      ownerEmail: 'vendor.lotusglam@raashilink.ai',
      businessName: 'Lotus Glam Lounge',
      category: 'Makeup',
      description: 'Coastal bridal makeup team specialising in soft glam, airbrush makeup, and luxury wedding prep.',
      city: 'Negombo',
      address: '90 Porutota Road, Negombo',
      contactPhone: '+94 77 389 1100',
      contactEmail: 'team@lotusglamlounge.example.com',
      website: 'https://lotusglamlounge.example.com',
      serviceArea: ['Negombo', 'Colombo', 'Chilaw'],
      pricingRange: { min: 40000, max: 200000, currency: 'LKR' },
      featuredServices: ['Airbrush makeup', 'Bride + mother styling', 'Salon prep'],
      packageSummary: ['Soft glam bridal', 'Airbrush luxury package', 'Bridal party styling'],
      responseTime: 'Usually responds within 4 hours',
      leadTimeDays: 7,
      capacity: { minGuests: 1, maxGuests: 10 },
      portfolioImages: [
        'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=75',
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=75',
      ],
      ratings: { average: 4.7, count: 22 },
    },
  ];

  await Promise.all(
    DEMO_VENDORS.map(async (v) => {
      const vendorOwner = await User.findOne({ email: v.ownerEmail }).select('_id');
      if (!vendorOwner) return;

      await Vendor.findOneAndUpdate(
        { businessName: v.businessName },
        {
          $set: {
            userId: vendorOwner._id,
            ...v,
            reviews: [],
            verified: true,
            availabilityCalendar: [],
          },
        },
        { upsert: true, new: true }
      );
    })
  );

  const horoscopeUsers = await User.find({ role: 'user' })
    .select('_id birthData horoscopeData')
    .lean({ virtuals: true });

  await Promise.all(
    horoscopeUsers.map(async (user) => {
      const sourceHoroscope = user.horoscope || (user.birthData
        ? {
            dateOfBirth: user.birthData.dateOfBirth,
            timeOfBirth: user.birthData.timeOfBirth,
            placeOfBirth: user.birthData.placeOfBirth,
            moonSign: user.horoscopeData?.moonSign,
            rashi: user.horoscopeData?.rashi,
            nakshatra: user.horoscopeData?.nakshatra,
          }
        : null);

      if (!sourceHoroscope) {
        return;
      }

      await Horoscope.findOneAndUpdate(
        { userId: user._id },
        {
          $set: {
            userId: user._id,
            zodiacSign: sourceHoroscope.moonSign || sourceHoroscope.rashi || 'Unknown',
            rashi: sourceHoroscope.rashi || sourceHoroscope.moonSign || 'Unknown',
            nakshatra: sourceHoroscope.nakshatra || 'Unknown',
            ascendant: user.horoscopeData?.ascendant || sourceHoroscope.moonSign || 'Unknown',
            planetaryPositions:
              user.horoscopeData?.planetaryPositions?.length > 0
                ? user.horoscopeData.planetaryPositions
                : [
                    {
                      planet: 'Sun',
                      sign: sourceHoroscope.moonSign || sourceHoroscope.rashi || 'Unknown',
                      house: 7,
                      degree: 12.4,
                    },
                  ],
            gunaScore: user.horoscopeData?.gunaScore || 0,
          },
        },
        { upsert: true, new: true }
      );
    })
  );

  await HoneymoonDestination.findOneAndUpdate(
    { country: 'Sri Lanka', region: 'Ella' },
    {
      $set: {
        country: 'Sri Lanka',
        region: 'Ella',
        description: 'Hill country escape with tea estates, scenic train rides, and boutique stays.',
        activityTags: ['nature', 'romantic', 'sightseeing'],
        budgetTier: 'mid-range',
        bestSeason: 'December to April',
        images: ['https://picsum.photos/seed/ella/1200/800'],
        highlights: ['Nine Arches Bridge', 'Little Adam\'s Peak', 'Tea plantation stays'],
      },
    },
    { upsert: true, new: true }
  );

  logger.info('Match scenario users ensured for development flow', { count: demoUsers.length });
}

export default {
  seedDemoUsers,
};
